<?php

class MyCoord
{

	public static $center = array('lat' => 34.81123119501047, 'lng' => 135.35563945770264);

	public static $kmlUrls = array(
		"https://raw.githubusercontent.com/kon104/tzuka/master/kml-sample-data/hananomichi-1st.kml",
		"https://raw.githubusercontent.com/kon104/tzuka/master/kml-sample-data/hananomichi-2nd.kml",
		"https://raw.githubusercontent.com/kon104/tzuka/master/kml-sample-data/hananomichi-3rd.kml",
		"https://raw.githubusercontent.com/kon104/tzuka/master/kml-sample-data/hananomichi-4th.kml",
		"https://raw.githubusercontent.com/kon104/tzuka/master/kml-sample-data/yoneya.kml"
	);

}

